services:
  db:
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_USER: rust
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: test
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rust"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  pgdata:
