[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
lapin = "3.7.2"
rand = "0.9.2"
tokio = {version = "1.47.1", features = ["full"]}
serde = {version ="1.0.219", features = ["derive"]}
serde_json = "1.0.143"
